### ISSUE TITLE
Need an Expression Tool mode

### ISSUE THREAD

**Issue by ghost** [rabix/cottontail-frontend#413]
Just like we have a `CommandlineTool` and `Workflow` editor, we should have an `ExpressionTool` editor. This editor would be largely like the `CommandlineTool` except that it would have no `dockerImage` field, no resource hints fields etc. and would create an `ExpressionTool` object. The workflow editor also needs to detect and understand `ExpressionTool` so it can be dropped into a canvas.

Please see [the specification](https://www.commonwl.org/v1.0/Workflow.html#ExpressionTool) for fields supported by `ExpressionTool`. As a template, this is a bit like `CommandlineTool` with most fields stripped out and an `expression` field substituted for `baseCommand`

A simple example `ExpressionTool` is:

```
class: ExpressionTool
cwlVersion: v1.0
expression: '$({"out": inputs.word1 + inputs.word2 })'
id: expr_tool
inputs:
- id: word1
    label: Word 1
    type: string
- id: word2
    label: Word 2
    type: string
outputs:
- id: out
    label: Word out
    type: string
```

A more detailed example `ExpressionTool`, shamelessly lifted from https://www.biostars.org/p/226272/#226360 is:

```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: ExpressionTool

requirements:
  - class: InlineJavascriptRequirement

inputs:
  filename:
    type: string
    outputBinding:
      outputEval: $(inputs.datafile.basename)
  filecontent:
    type: string
    outputBinding:
      outputEval: $(inputs.datafile.contents)
  datafile:
    type: File
    inputBinding:
      loadContents: true

outputs:
  processedoutput:
    type: Any

expression: "${var lines = inputs.datafile.contents.split('\\n');
               var nblines = lines.length;
               var arrayofarrays = [];
               var setofarrays = {};
               for (var i = 0; i < nblines; i++) {
                  arrayofarrays.push(lines[i].split(','));
                  setofarrays[i] = lines[i].split(',');}
               return { 'processedoutput': setofarrays } ;
              }"
```

Needed to help out #407
