### ISSUE TITLE
RC should understand and deal with/generate alternative syntax for type definitions

### ISSUE THREAD

**Issue by ghost** [rabix/cottontail-frontend#415]
RC should understand and deal with/generate alternative syntax for type definitions
```
  - id: reads
    type:
      type: array
      items: File
      inputBinding: { prefix: "-YYY" }
```

Possibly related to #414
